### ISSUE TITLE
yanagishima conf

### ISSUE THREAD

**Issue by NextMark** [wyukawa/yanagishima#12]
Hi wyukawa
      I use the conf as following, but when I click demo button, the exception as follows.

```
jetty.port=8001
presto.query.max-run-time-seconds=1800
presto.max-result-file-byte-size=1073741824
presto.datasources=demo
presto.coordinator.server.your-presto=http://localhost:8080
presto.redirect.server.your-presto=http://localhost:8080
catalog.your-presto=hive
schema.your-presto=default
select.limit=500
audit.http.header.name=some.auth.header
```

```
2017/04/21 10:51:38.648 +0800 ERROR [PrestoServlet] [Yanagishima] No value present
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at yanagishima.config.YanagishimaConfig.getPrestoCoordinatorServer(YanagishimaConfig.java:17)
	at yanagishima.service.PrestoServiceImpl.getStatementClient(PrestoServiceImpl.java:212)
	at yanagishima.service.PrestoServiceImpl.doQuery(PrestoServiceImpl.java:57)
	at yanagishima.servlet.PrestoServlet.lambda$doPost$4(PrestoServlet.java:79)
	at java.util.Optional.ifPresent(Optional.java:159)
	at yanagishima.servlet.PrestoServlet.doPost(PrestoServlet.java:72)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:287)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:277)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:182)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:119)
	at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:133)
	at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:130)
	at com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:203)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:130)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at yanagishima.filter.YanagishimaFilter.doFilter(YanagishimaFilter.java:17)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:745)

```

    Could you please show me your conf?

**Comment by wyukawa** [comment]
please try following setting
```
jetty.port=8001
presto.query.max-run-time-seconds=1800
presto.max-result-file-byte-size=1073741824
presto.datasources=demo
presto.coordinator.server.demo=http://localhost:8080
presto.redirect.server.demo=http://localhost:8080
catalog.demo=hive
schema.demo=default
select.limit=500
audit.http.header.name=some.auth.header
```

**Comment by NextMark** [comment]
It's work, thanks.
