### ISSUE TITLE
CSV for UTF-8

### ISSUE THREAD

**Issue by imperio-wxm** [wyukawa/yanagishima#13]
When I read /src/main/java/yanagishima/util/DownloadUtil.java，I found csvDownload method in the character encoding for Shift_JIS, Chinese will be garbled, can be changed to UTF-8?

**However, when I try to modify the encoding format for UTF-8, and recompiling, run the error as follows:**

```java
2017/05/04 08:34:34.965 -0700 ERROR [PrestoServlet] [Yanagishima] Missing required header 'X-yanagishima-datasources'.
java.lang.RuntimeException: Missing required header 'X-yanagishima-datasources'.
	at yanagishima.util.HttpRequestUtil.getHeader(HttpRequestUtil.java:20)
	at yanagishima.util.AccessControlUtil.checkDatasource(AccessControlUtil.java:14)
	at yanagishima.servlet.PrestoServlet.lambda$doPost$4(PrestoServlet.java:80)
	at java.util.Optional.ifPresent(Optional.java:159)
	at yanagishima.servlet.PrestoServlet.doPost(PrestoServlet.java:76)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:287)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:277)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:182)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:119)
	at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:133)
	at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:130)
	at com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:203)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:130)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at yanagishima.filter.YanagishimaFilter.doFilter(YanagishimaFilter.java:22)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by wyukawa** [comment]
hmm, yanagishima stores CSV for Shift_JIS because Japanese is not garbled in Excel.
So, I can't change.

If you want to use CSV for UTF-8, you can git clone version 3 tag, and edit DownloadUtil.java and build.

Althogth yanagishima has a authorization feature, reverse proxy and some manual procedures are necessary. So I tune off it in version 3 tag.
But in master branch, authorization feature is on because we use it.
This is the reason why you encountered to stacktrace.

And yanagishima UI and backend API development is separated in our environment and it's not synchronized to push to github.com

As a conclusion, I don't recommend to use master branch.
So please use 3.0 tag.

**Comment by imperio-wxm** [comment]
@wyukawa Thx,I modified the character encoding and compiled v3.0 tag. It works.
