### ISSUE TITLE
Missing required parameter 'datasource'

### ISSUE THREAD

**Issue by rusonding** [wyukawa/yanagishima#19]
conf:
jetty.port=8082
presto.query.max-run-time-seconds=1800
presto.max-result-file-byte-size=1073741824
presto.datasources=presto1
presto.coordinator.server.presto1=http://node1:9090
presto.redirect.server.presto1=http://node1:9090
catalog.presto1=hive
schema.presto1=default
select.limit=500
audit.http.header.name=some.auth.header
to.values.query.limit=500
check.datasource=false

2017/06/09 17:07:59.193 +0800 WARN [ServletHandler] [Yanagishima] /query
java.lang.RuntimeException: Missing required parameter 'datasource'.
	at yanagishima.util.HttpRequestUtil.getParam(HttpRequestUtil.java:11)
	at yanagishima.servlet.QueryServlet.doGet(QueryServlet.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:287)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:277)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:182)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:119)
	at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:133)
	at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:130)
	at com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:203)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:130)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at yanagishima.filter.YanagishimaFilter.doFilter(YanagishimaFilter.java:22)

**Comment by wyukawa** [comment]
Which version do you use?
Please follow issue template.

If check.datasource=false, such kind of exception shouldn't occur.

**Comment by sudhirsrepo** [comment]
@wyukawa , Nope its not working even though the property check.datasource=false.

@rusonding , my workaround goes here,

My Presto config (etc/catalog/hive.config)
`connector.name=hive-hadoop2`
Update the datasource in Yanagishima.properties same as connector.name properties value in above hive.config
`resto.datasources=hive-hadoop2 `


The final hive.properties in presto should be something like 

```
jetty.port=8082
presto.query.max-run-time-seconds=1800
presto.max-result-file-byte-size=1073741824
presto.datasources=hive-hadoop2 
presto.coordinator.server.hive-hadoop2=http://localhost:8080
presto.redirect.server.hive-hadoop2=http://localhost:8080
catalog.hive-hadoop2=hive
schema.hive-hadoop2=default
select.limit=500
to.values.query.limit=500
check.datasource=false
```


Cheers ....

**Comment by wyukawa** [comment]
It's weird because ```presto.datasources``` in yanagishima.properties can be any name.
It's not necessary same as ```connector.name``` in hive.properties.

**Comment by rusonding** [comment]
@wyukawa
sql: select count(1) from test.t1

017/06/11 08:45:45.620 +0800 ERROR [PrestoServiceImpl] [Yanagishima] java.sql.SQLException: Query failed (#20170611_004545_00064_cxmdv): null
yanagishima.exception.QueryErrorException: java.sql.SQLException: Query failed (#20170611_004545_00064_cxmdv): null
	at yanagishima.service.PrestoServiceImpl.resultsException(PrestoServiceImpl.java:312)
	at yanagishima.service.PrestoServiceImpl.getPrestoQueryResult(PrestoServiceImpl.java:170)
	at yanagishima.service.PrestoServiceImpl.access$100(PrestoServiceImpl.java:41)
	at yanagishima.service.PrestoServiceImpl$Task.run(PrestoServiceImpl.java:88)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: Query failed (#20170611_004545_00064_cxmdv): null
	... 9 more
Caused by: java.lang.NullPointerException
